### ISSUE TITLE
DOCTYPE lost when the template is a complete document

### ISSUE THREAD

**Issue by papandreou** [Munawwar/htmlizer#10]
```
$ node -p -e 'new (require("htmlizer"))("<!DOCTYPE html>\n<html><head></head><body></body></html>").toString()'

<html><head></head><body></body></html>
```

Expected output:
```
<!DOCTYPE html>
<html><head></head><body></body></html>
```

**Comment by Munawwar** [comment]
Summarizing this:
Upgrading to jsdom 3.1.2 makes jQuery.parseHTML removes doctype,html,body and head tags.
On jsdom 0.10.3 jQuery.parseHTML removes doctype.
jsdom.jsdom() function only returns a Document type, hence it will *always* have html,head,body tag even for html fragments.

So I am going to experiment with [neutron-html5parser](https://github.com/Munawwar/neutron-html5parser) on a branch.

**Comment by Munawwar** [comment]
This one will be fixed with Htmlizer v2.

**Comment by papandreou** [comment]
Fantastic, thanks for keeping it in mind :)

**Comment by Munawwar** [comment]
Fixed with v2.
