### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by Munawwar** [Munawwar/htmlizer#13]
There are two things that I'd like to update:
1. Sizzle [now supports](https://github.com/jquery/sizzle/issues/284) selectors in documentfragment.
So get rid of helper functions and use Sizzle instead.
2. Move away from assert and use [expected](https://github.com/Automattic/expect.js) or [unexpected](https://github.com/sunesimonsen/unexpected).

**Comment by Munawwar** [comment]
Closing issue:
1. jsdom support querySelector() on DocumentFragment.
2. Use asset.strictEqual(), instead of assert.equal().

**Comment by papandreou** [comment]
Let me know if you need help adopting Unexpected and relevant plugins :)

**Comment by Munawwar** [comment]
Don't think unexpected can make things simpler than it already is.
