### ISSUE TITLE
add support for nodejs 4.0

### ISSUE THREAD

**Issue by gustavnikolaj** [Munawwar/htmlizer#19]
Currently we cannot build htmlizer under nodejs 4.0 as the jsdom dependency is too old.

I'm not sure if there's a version of jsdom that works across all node.js versions.

**Comment by papandreou** [comment]
@gustavnikolaj Try this: https://github.com/assetgraph/assetgraph-builder/commit/83c9010e6ca5af1ac0fe5857e6f55a1b32283e34

**Comment by Munawwar** [comment]
With v2, jsdom is now only a dev dependency (which allows any version). So I think v2 now supports node v4. (Didn't test it yet. Reopen if it is isn't working).
