### ISSUE TITLE
Update jsdom in htmlizer 0.x

### ISSUE THREAD

**Issue by mwoc** [Munawwar/htmlizer#21]
We're using htmlizer 0.8.0 in a project we wish to update to node v6, without updating to htmlizer v2 in the same iteration. This breaks due to jsdom's interface supposedly breaking when recompiling on nodejs v6:

___/htmlizer/node_modules/jsdom/lib/jsdom/level1/core.js:553
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild);
                             ^

TypeError: Cannot set property length of [object Object] which has only a getter
    at DocumentFragment.core.Node.insertBefore (___/htmlizer/node_modules/jsdom/lib/jsdom/level1/core.js:553:30)
    at DocumentFragment.<anonymous> (___/htmlizer/node_modules/jsdom/lib/jsdom/level2/events.js:332:20)
    at DocumentFragment.proto.(anonymous function) [as insertBefore] (___/htmlizer/node_modules/jsdom/lib/jsdom/utils.js:23:26)
    at DocumentFragment.core.Node.appendChild (___/htmlizer/node_modules/jsdom/lib/jsdom/level1/core.js:671:17)
    at ___/htmlizer/src/jquery.js:3:2360
    at ___/htmlizer/src/jquery.js:3:2615
    at b.object.module.object.module.exports.module.exports (___/htmlizer/src/jquery.js:2:201)
    at window (___/htmlizer/src/Htmlizer.js:15:32)
    at Object.<anonymous> (___/htmlizer/src/Htmlizer.js:24:2)

I tested with small increments to the jsdom version, and found that updating from 0.10.3 to 1.5.0 seems enough. For now, we've made a fork at https://github.com/mwoc/htmlizer/tree/v0 with this update, which probably is ok - but if others might need htmlizer v0.x to work on nodejs v6, then maybe an official patch might be worthwhile.

**Comment by Munawwar** [comment]
Is it ok if I update to jsdom 9.2.1?

**Comment by Munawwar** [comment]
Ok, now I remember why I didn't update jsdom.

Htmlizer relies on jQuery.parseHTML for parsing HTML string to DOM nodes.
Upgrading to jsdom 3.1.2 or higher makes jQuery.parseHTML removes doctype,html,body and head tags. On jsdom 0.10.3 jQuery.parseHTML removes doctype only. Upgrading jsdom would cause a regression for anyone parsing entire documents (like [here](https://github.com/Munawwar/htmlizer/issues/10)).

As a workaround, now I detect if document begins with a &lt;html&gt; tag and then use a [different parsing trick](https://github.com/Munawwar/htmlizer/commit/bca1680bc5edb8116493f2f9c96ee6d700c54a96#diff-59b888c827c2b1842da367b7ac02cd61R567). The limitation are:
1. you can't parse a template that *begins* with a head or body tag. They will have to be wrapped inside an html tag.
2. An empty head tag will always be present when parsing an entire document (I can work around that as well, but didn't, as it won't cause much harm I guess).

**Comment by papandreou** [comment]
@mwoc, upgrading to htmlizer 2 should be far easier. It doesn't depend on jsdom at all (except as a dev dep), is faster and has the same API (iirc).

**Comment by Munawwar** [comment]
@mwoc Yea, very few things have changed in htmlizer2:
```
1. toDocumentFragment() method has been removed.
2. $element KO binding context cannot be used anymore.
3. template binding interface has changed. (It has become simpler).
```

BTW, has anyone noticed that knockout itself can be run on node (by first declaring a global window and document object)? As far as I've tested it, even ko.observable and change updates also works.

**Comment by mwoc** [comment]
I'll take a look at upgrading to v2 then. I think I tried while I was upgrading to node v6, and something else broke when using htmlizer, probably hitting one of the API changes. Will let you know how it goes this time  :)

**Comment by Munawwar** [comment]
@mwoc Did you solve your issues with v2?

**Comment by mwoc** [comment]
I'm working now on updating to v2, and ran into issue #22 which I now remember earlier was the reason why I wanted to stick to v0.x for now.
